import { describe, expect, it } from 'vitest'

// TASK #980 integration tests, against the REAL audit reports produced by
// Task #979 on real prospect websites.
//
// Nothing here delivers anything: no email, no publish, no CRM write. The
// workflow ends at a status, which is the whole point of the task.

async function ready(): Promise<string | null> {
  if (process.env.CRM_DRIVER !== 'real') return `CRM_DRIVER is "${process.env.CRM_DRIVER}", not "real"`
  try {
    const { prisma } = await import('../../src/platform/db.js')
    await prisma.$queryRaw`SELECT 1`
  } catch (err) {
    return `marketing database unavailable: ${(err as Error).message}`
  }
  return null
}

const skipReason = await ready()
const describeIfReady = skipReason ? describe.skip : describe
if (skipReason) console.warn(`\n[audit-approval] SKIPPED — ${skipReason}\n`)

const REVIEWER = {
  crmUserId: 'crm-user-reviewer-a',
  email: 'reviewer-a@deeptechskills.com',
  name: 'Reviewer A',
  tenantId: '',
}
const REVIEWER_B = {
  crmUserId: 'crm-user-reviewer-b',
  email: 'reviewer-b@deeptechskills.com',
  name: 'Reviewer B',
  tenantId: '',
}

async function tenantId(): Promise<string> {
  const { prisma } = await import('../../src/platform/db.js')
  const t = await prisma.tenant.findFirstOrThrow({ where: { slug: process.env.DEFAULT_TENANT_SLUG } })
  return t.id
}

/**
 * A disposable copy of a real report, so the tests exercise real evidence
 * without leaving the shared reports in a reviewed state.
 */
async function cloneRealReport(preferFindings = true) {
  const { prisma, newId } = await import('../../src/platform/db.js')
  const tid = await tenantId()

  const source = await prisma.websiteAuditRun.findFirst({
    where: { tenantId: tid, ...(preferFindings ? { productPages: { gt: 0 } } : {}) },
    orderBy: { productPages: 'desc' },
  })
  if (!source) return null

  const sourceReport = await prisma.auditReport.findUnique({ where: { auditRunId: source.id } })
  if (!sourceReport) return null

  const pages = await prisma.auditedPage.findMany({ where: { auditRunId: source.id } })
  const observations = await prisma.pageObservation.findMany({ where: { auditRunId: source.id } })
  const findings = await prisma.catalogFinding.findMany({ where: { auditRunId: source.id } })

  const runId = newId()
  const { id: _sourceId, ...runRest } = source
  await prisma.websiteAuditRun.create({ data: { ...runRest, id: runId } })

  const pageIdMap = new Map<string, string>()
  for (const p of pages) {
    const newPageId = newId()
    pageIdMap.set(p.id, newPageId)
    const { id: _p, ...rest } = p
    await prisma.auditedPage.create({ data: { ...rest, id: newPageId, auditRunId: runId } })
  }

  const obsIdMap = new Map<string, string>()
  for (const o of observations) {
    const newObsId = newId()
    obsIdMap.set(o.id, newObsId)
    const { id: _o, ...rest } = o
    await prisma.pageObservation.create({
      data: { ...rest, id: newObsId, auditRunId: runId, pageId: pageIdMap.get(o.pageId)! },
    })
  }

  for (const f of findings) {
    const { id: _f, ...rest } = f
    // Evidence references are remapped so they resolve against the clone —
    // otherwise the evidence-resolution check would pass for the wrong reason.
    const evidence = ((f.evidence ?? []) as Array<Record<string, unknown>>).map((e) => {
      const oldId = String(e.observationId)
      const remapped = oldId.startsWith('page:')
        ? `page:${pageIdMap.get(oldId.slice(5)) ?? oldId.slice(5)}`
        : (obsIdMap.get(oldId) ?? oldId)
      return { ...e, observationId: remapped, pageId: pageIdMap.get(String(e.pageId)) ?? e.pageId }
    })
    await prisma.catalogFinding.create({
      data: { ...rest, id: newId(), auditRunId: runId, evidence: evidence as never },
    })
  }

  const { id: _r, ...reportRest } = sourceReport
  const report = await prisma.auditReport.create({
    data: {
      ...reportRest,
      id: newId(),
      auditRunId: runId,
      status: 'ready_for_approval',
      currentRevision: 1,
      lockVersion: 1,
      approvedRevision: null,
      reviewerCrmUserId: null,
      approvalValidation: undefined,
    },
  })

  await prisma.auditReportRevision.create({
    data: {
      id: newId(),
      tenantId: tid,
      auditReportId: report.id,
      auditRunId: runId,
      revisionNumber: 1,
      content: sourceReport.collateral as never,
      pdfBytes: sourceReport.pdfBytes,
      pdfSha256: sourceReport.pdfSha256,
      pdfPageCount: sourceReport.pdfPageCount,
      pdfBytesSize: sourceReport.pdfBytesSize,
      changeReason: 'Generated by the website audit (Task #979).',
      validationOk: false,
    },
  })

  return { runId, reportId: report.id, tenantId: tid, companyName: source.companyName }
}

async function cleanup(runId: string) {
  const { prisma } = await import('../../src/platform/db.js')
  await prisma.websiteAuditRun.delete({ where: { id: runId } }).catch(() => undefined)
}

describeIfReady('Task #980 — approval workflow against real audit reports', () => {
  it('CASE 1: reviewer edits wording, saves revision 2, then approves it', async () => {
    const { reviseReport, transition } = await import('../../src/websiteaudit/approvalService.js')
    const { prisma } = await import('../../src/platform/db.js')

    const c = await cloneRealReport()
    if (!c) return
    const reviewer = { ...REVIEWER, tenantId: c.tenantId }

    try {
      const started = await transition({
        tenantId: c.tenantId,
        auditRunId: c.runId,
        reviewer,
        action: 'start',
        concurrency: { expectedLockVersion: 1 },
      })
      expect(started.status).toBe('in_review')

      const revised = await reviseReport({
        tenantId: c.tenantId,
        auditRunId: c.runId,
        reviewer,
        edit: { nextStep: 'Book a 20-minute call to walk through the pages cited in this report.' },
        changeReason: 'Sharper call to action.',
        concurrency: { expectedLockVersion: started.lockVersion },
      })

      expect(revised.revisionNumber).toBe(2)
      expect(revised.sourceRevisionNumber).toBe(1)
      expect(revised.validation.ok, JSON.stringify(revised.validation.errors)).toBe(true)

      // A new PDF, with a different digest from revision 1.
      const [r1, r2] = await Promise.all([
        prisma.auditReportRevision.findUniqueOrThrow({
          where: { auditReportId_revisionNumber: { auditReportId: c.reportId, revisionNumber: 1 } },
        }),
        prisma.auditReportRevision.findUniqueOrThrow({
          where: { auditReportId_revisionNumber: { auditReportId: c.reportId, revisionNumber: 2 } },
        }),
      ])
      expect(r2.pdfSha256).not.toBe(r1.pdfSha256)
      expect(r2.pdfBytesSize).toBeGreaterThan(1000)

      const approved = await transition({
        tenantId: c.tenantId,
        auditRunId: c.runId,
        reviewer,
        action: 'approve',
        comment: 'Reads well and every figure checks out.',
        concurrency: { expectedLockVersion: revised.lockVersion },
      })
      expect(approved.status).toBe('approved')
      expect(approved.validation?.ok).toBe(true)

      const final = await prisma.auditReport.findUniqueOrThrow({ where: { id: c.reportId } })
      expect(final.approvedRevision).toBe(2)
      expect(final.reviewerCrmUserId).toBe(reviewer.crmUserId)
      expect(final.approvalValidation).toBeTruthy()
    } finally {
      await cleanup(c.runId)
    }
  }, 180_000)

  it('CASE 2: reviewer requests changes, a revision follows, review resumes', async () => {
    const { reviseReport, transition } = await import('../../src/websiteaudit/approvalService.js')
    const { prisma } = await import('../../src/platform/db.js')

    const c = await cloneRealReport()
    if (!c) return
    const reviewer = { ...REVIEWER, tenantId: c.tenantId }

    try {
      const changes = await transition({
        tenantId: c.tenantId,
        auditRunId: c.runId,
        reviewer,
        action: 'request_changes',
        comment: 'Correct the wording in recommendation 1.',
        concurrency: { expectedLockVersion: 1 },
      })
      expect(changes.status).toBe('changes_requested')

      // Requesting changes must NOT regenerate anything on its own.
      const revisionsAfter = await prisma.auditReportRevision.count({ where: { auditReportId: c.reportId } })
      expect(revisionsAfter).toBe(1)

      const revised = await reviseReport({
        tenantId: c.tenantId,
        auditRunId: c.runId,
        reviewer,
        edit: { recommendedImprovementAreas: ['Publish a consistent specification block on each product page.'] },
        changeReason: 'Reworded recommendation 1 as requested.',
        concurrency: { expectedLockVersion: changes.lockVersion },
      })
      expect(revised.revisionNumber).toBe(2)

      const back = await transition({
        tenantId: c.tenantId,
        auditRunId: c.runId,
        reviewer,
        action: 'start',
        concurrency: { expectedLockVersion: revised.lockVersion },
      })
      expect(back.status).toBe('in_review')

      const history = await prisma.auditApprovalEvent.findMany({
        where: { auditReportId: c.reportId },
        orderBy: { createdAt: 'asc' },
      })
      expect(history.map((h) => h.action)).toEqual(['request_changes', 'revise', 'start'])
      expect(history[0]!.comment).toBe('Correct the wording in recommendation 1.')
      expect(history.every((h) => h.reviewerCrmUserId === reviewer.crmUserId)).toBe(true)
    } finally {
      await cleanup(c.runId)
    }
  }, 180_000)

  it('CASE 3: an edit that changes an evidence-backed metric is refused', async () => {
    const { reviseReport } = await import('../../src/websiteaudit/approvalService.js')

    const c = await cloneRealReport()
    if (!c) return
    const reviewer = { ...REVIEWER, tenantId: c.tenantId }

    try {
      // The reviewer cannot reach a metric field, so the attempt takes the only
      // route left: typing a different number into prose.
      const revised = await reviseReport({
        tenantId: c.tenantId,
        auditRunId: c.runId,
        reviewer,
        edit: { summary: 'Specifications were observed on 999 of 1000 inspected product pages.' },
        changeReason: 'Attempting to overstate the sample.',
        concurrency: { expectedLockVersion: 1 },
      })

      expect(revised.validation.ok).toBe(false)
      const quantitative = revised.validation.errors.filter((e) => e.check === 'quantitative_claims')
      expect(quantitative.length).toBeGreaterThan(0)
      expect(quantitative[0]!.message).toMatch(/does not match any count this audit recorded/)
    } finally {
      await cleanup(c.runId)
    }
  }, 180_000)

  it('CASE 4: approval is blocked while a revision carries an unsupported claim', async () => {
    const { reviseReport, transition } = await import('../../src/websiteaudit/approvalService.js')
    const { prisma } = await import('../../src/platform/db.js')

    const c = await cloneRealReport()
    if (!c) return
    const reviewer = { ...REVIEWER, tenantId: c.tenantId }

    try {
      const revised = await reviseReport({
        tenantId: c.tenantId,
        auditRunId: c.runId,
        reviewer,
        edit: { nextStep: 'Fixing this is guaranteed to lift your revenue by 30% within a quarter.' },
        changeReason: 'Adding a stronger close.',
        concurrency: { expectedLockVersion: 1 },
      })
      expect(revised.validation.ok).toBe(false)

      await expect(
        transition({
          tenantId: c.tenantId,
          auditRunId: c.runId,
          reviewer,
          action: 'approve',
          concurrency: { expectedLockVersion: revised.lockVersion },
        }),
      ).rejects.toThrow(/validation failed/i)

      // The report did not move, and the refused attempt is in the trail.
      const report = await prisma.auditReport.findUniqueOrThrow({ where: { id: c.reportId } })
      expect(report.status).toBe('ready_for_approval')
      expect(report.approvedRevision).toBeNull()

      const blocked = await prisma.auditApprovalEvent.findFirst({
        where: { auditReportId: c.reportId, action: 'approve_blocked' },
      })
      expect(blocked).toBeTruthy()
      expect(blocked!.reviewerCrmUserId).toBe(reviewer.crmUserId)
    } finally {
      await cleanup(c.runId)
    }
  }, 180_000)

  it('CASE 5: a stale write from a second reviewer is rejected', async () => {
    const { reviseReport, transition } = await import('../../src/websiteaudit/approvalService.js')

    const c = await cloneRealReport()
    if (!c) return
    const a = { ...REVIEWER, tenantId: c.tenantId }
    const b = { ...REVIEWER_B, tenantId: c.tenantId }

    try {
      // Both reviewers load the report and see lockVersion 1.
      const seenByA = 1
      const seenByB = 1

      // B acts first.
      const bResult = await transition({
        tenantId: c.tenantId,
        auditRunId: c.runId,
        reviewer: b,
        action: 'start',
        concurrency: { expectedLockVersion: seenByB },
      })
      expect(bResult.lockVersion).toBe(2)

      // A now tries to save against the version they were shown.
      await expect(
        reviseReport({
          tenantId: c.tenantId,
          auditRunId: c.runId,
          reviewer: a,
          edit: { summary: 'An edit written against a stale view.' },
          changeReason: 'Concurrent edit.',
          concurrency: { expectedLockVersion: seenByA },
        }),
      ).rejects.toThrow(/changed since you loaded it/i)
    } finally {
      await cleanup(c.runId)
    }
  }, 180_000)

  it('preserves revision 1 byte-for-byte through the whole workflow', async () => {
    const { reviseReport } = await import('../../src/websiteaudit/approvalService.js')
    const { prisma } = await import('../../src/platform/db.js')
    const { createHash } = await import('node:crypto')

    const c = await cloneRealReport()
    if (!c) return
    const reviewer = { ...REVIEWER, tenantId: c.tenantId }

    try {
      const before = await prisma.auditReportRevision.findUniqueOrThrow({
        where: { auditReportId_revisionNumber: { auditReportId: c.reportId, revisionNumber: 1 } },
      })

      let lock = 1
      for (let i = 0; i < 2; i++) {
        const r = await reviseReport({
          tenantId: c.tenantId,
          auditRunId: c.runId,
          reviewer,
          edit: { summary: `Rewritten summary, pass ${i + 1}.` },
          changeReason: `Edit ${i + 1}`,
          concurrency: { expectedLockVersion: lock },
        })
        lock = r.lockVersion
      }

      const after = await prisma.auditReportRevision.findUniqueOrThrow({
        where: { auditReportId_revisionNumber: { auditReportId: c.reportId, revisionNumber: 1 } },
      })

      expect(after.pdfSha256).toBe(before.pdfSha256)
      expect(JSON.stringify(after.content)).toBe(JSON.stringify(before.content))
      // The digest still describes the bytes actually stored.
      expect(createHash('sha256').update(Buffer.from(after.pdfBytes!)).digest('hex')).toBe(after.pdfSha256)

      const all = await prisma.auditReportRevision.findMany({
        where: { auditReportId: c.reportId },
        orderBy: { revisionNumber: 'asc' },
      })
      expect(all.map((r) => r.revisionNumber)).toEqual([1, 2, 3])
      // Every revision keeps its own PDF and its own digest.
      expect(new Set(all.map((r) => r.pdfSha256)).size).toBe(3)
    } finally {
      await cleanup(c.runId)
    }
  }, 240_000)

  it('an approved report cannot be edited or regenerated', async () => {
    const { reviseReport, transition } = await import('../../src/websiteaudit/approvalService.js')
    const { generateAuditReport } = await import('../../src/websiteaudit/report.js')

    const c = await cloneRealReport()
    if (!c) return
    const reviewer = { ...REVIEWER, tenantId: c.tenantId }

    try {
      const approved = await transition({
        tenantId: c.tenantId,
        auditRunId: c.runId,
        reviewer,
        action: 'approve',
        comment: 'Approved as generated.',
        concurrency: { expectedLockVersion: 1 },
      })
      expect(approved.status).toBe('approved')

      await expect(
        reviseReport({
          tenantId: c.tenantId,
          auditRunId: c.runId,
          reviewer,
          edit: { summary: 'Changing an approved report.' },
          changeReason: 'Should be refused.',
          concurrency: { expectedLockVersion: approved.lockVersion },
        }),
      ).rejects.toThrow(/cannot be edited/i)

      // Regeneration would delete the approved revision and reset the status.
      await expect(generateAuditReport(c.runId)).rejects.toThrow(/cannot be regenerated/i)

      await expect(
        transition({
          tenantId: c.tenantId,
          auditRunId: c.runId,
          reviewer,
          action: 'request_changes',
          comment: 'Trying to reopen the wrong way.',
          concurrency: { expectedLockVersion: approved.lockVersion },
        }),
      ).rejects.toThrow(/cannot be sent back for changes/i)
    } finally {
      await cleanup(c.runId)
    }
  }, 180_000)

  it('a rejected report is terminal and carries its reason', async () => {
    const { transition } = await import('../../src/websiteaudit/approvalService.js')
    const { prisma } = await import('../../src/platform/db.js')

    const c = await cloneRealReport()
    if (!c) return
    const reviewer = { ...REVIEWER, tenantId: c.tenantId }

    try {
      const rejected = await transition({
        tenantId: c.tenantId,
        auditRunId: c.runId,
        reviewer,
        action: 'reject',
        comment: 'The crawl sample is too thin to send to this account.',
        concurrency: { expectedLockVersion: 1 },
      })
      expect(rejected.status).toBe('rejected')
      expect(rejected.availableActions).toEqual(['reopen'])

      const report = await prisma.auditReport.findUniqueOrThrow({ where: { id: c.reportId } })
      expect(report.decisionComment).toMatch(/too thin/)
      // Nothing marks it as deliverable.
      expect(report.approvedRevision).toBeNull()
    } finally {
      await cleanup(c.runId)
    }
  }, 120_000)

  it('requires a reason for the decisions that need one', async () => {
    const { transition } = await import('../../src/websiteaudit/approvalService.js')

    const c = await cloneRealReport()
    if (!c) return
    const reviewer = { ...REVIEWER, tenantId: c.tenantId }

    try {
      for (const action of ['request_changes', 'reject'] as const) {
        await expect(
          transition({
            tenantId: c.tenantId,
            auditRunId: c.runId,
            reviewer,
            action,
            concurrency: { expectedLockVersion: 1 },
          }),
        ).rejects.toThrow(/comment is required/i)
      }
    } finally {
      await cleanup(c.runId)
    }
  }, 120_000)

  it('reopening an approved report starts a new cycle without destroying the approved revision', async () => {
    const { transition } = await import('../../src/websiteaudit/approvalService.js')
    const { prisma } = await import('../../src/platform/db.js')

    const c = await cloneRealReport()
    if (!c) return
    const reviewer = { ...REVIEWER, tenantId: c.tenantId }

    try {
      const approved = await transition({
        tenantId: c.tenantId,
        auditRunId: c.runId,
        reviewer,
        action: 'approve',
        comment: 'Approved.',
        concurrency: { expectedLockVersion: 1 },
      })

      const reopened = await transition({
        tenantId: c.tenantId,
        auditRunId: c.runId,
        reviewer,
        action: 'reopen',
        comment: 'The client asked for a different emphasis.',
        concurrency: { expectedLockVersion: approved.lockVersion },
      })
      expect(reopened.status).toBe('in_review')

      // The revision that was approved is still there, unchanged.
      const r1 = await prisma.auditReportRevision.findUniqueOrThrow({
        where: { auditReportId_revisionNumber: { auditReportId: c.reportId, revisionNumber: 1 } },
      })
      expect(r1.validationOk).toBe(true)

      const events = await prisma.auditApprovalEvent.findMany({
        where: { auditReportId: c.reportId },
        orderBy: { createdAt: 'asc' },
      })
      expect(events.map((e) => e.action)).toEqual(['approve', 'reopen'])
      expect(events[1]!.previousStatus).toBe('approved')
    } finally {
      await cleanup(c.runId)
    }
  }, 180_000)

  it('records the reviewer from the caller, with no way to spoof identity', async () => {
    const { transition } = await import('../../src/websiteaudit/approvalService.js')
    const { prisma } = await import('../../src/platform/db.js')

    const c = await cloneRealReport()
    if (!c) return

    try {
      await transition({
        tenantId: c.tenantId,
        auditRunId: c.runId,
        // Routes populate this from req.principal; there is no body field for it.
        reviewer: { ...REVIEWER_B, tenantId: c.tenantId },
        action: 'start',
        concurrency: { expectedLockVersion: 1 },
      })

      const event = await prisma.auditApprovalEvent.findFirstOrThrow({ where: { auditReportId: c.reportId } })
      expect(event.reviewerCrmUserId).toBe(REVIEWER_B.crmUserId)
      expect(event.reviewerEmail).toBe(REVIEWER_B.email)
      expect(event.reviewerName).toBe(REVIEWER_B.name)
    } finally {
      await cleanup(c.runId)
    }
  }, 120_000)

  it('the approval trail has no update or delete path in the codebase', async () => {
    // A grep-level guarantee: immutability enforced by absence of code, not by
    // a convention someone can forget.
    const { readFileSync, readdirSync } = await import('node:fs')
    const { join } = await import('node:path')

    const files: string[] = []
    const walk = (dir: string) => {
      for (const e of readdirSync(dir, { withFileTypes: true })) {
        const p = join(dir, e.name)
        if (e.isDirectory()) walk(p)
        else if (e.name.endsWith('.ts')) files.push(p)
      }
    }
    walk('src')

    const offenders = files.filter((f) => {
      const s = readFileSync(f, 'utf8')
      return /auditApprovalEvent\.(update|updateMany|delete|deleteMany|upsert)\b/.test(s)
    })
    expect(offenders).toEqual([])
  })
})
