import { assertSupported } from './claimGuard.js'
import type { CatalogFinding } from './findings.js'

// PHASE 6 — the business-value layer.
//
// BUSINESS SOURCE: Team Answer Sections F.3/F.4 and the Phase 6 brief, which
// asks for each finding to be readable as a business conversation rather than
// a defect list:
//
//   OBSERVATION -> BUSINESS PAIN -> WHY IT MATTERS -> POTENTIAL OPPORTUNITY
//   -> RECOMMENDED DIRECTION
//
// Two constraints shape every line below.
//
// FIRST: nothing here is generated by a model. Each finding CODE maps to a
// written interpretation, chosen once and reviewed once. A model asked to
// write the business pain for a finding would write something plausible and
// occasionally something indefensible, and the whole point of this engine is
// that a salesperson can put the output in front of a prospect without
// reading it first. Deterministic mapping is also the only version that can
// be tested.
//
// SECOND: the causal chain stops where the evidence stops. Better product
// data makes products easier to find and compare. Whether that earns the
// customer money is not something a page sample can establish, so this file
// says "potential opportunity" and marks financial analysis as not quantified.
// The claim guard enforces it; the language here is written so the guard
// never has to fire.

export interface BusinessPain {
  findingCode: string
  /** What was seen, in the finding's own sample-scoped terms. */
  observation: string
  /** What that may cost the buyer's customer, stated as a possibility. */
  businessPain: string
  whyItMatters: string
  potentialOpportunity: string
  recommendedDirection: string
}

export interface BusinessValue {
  whatWeObserved: string
  whyThisMatters: string
  whereThePainMayAppear: string
  howAltiusNxtCanHelp: string
  improvedExperience: string
  nextStep: string
  /** Required by the brief: financial impact is never implied. */
  financialNote: string
}

export const DISCOVERABILITY_LENSES = ['seo', 'aeo', 'geo'] as const
export type DiscoverabilityLens = (typeof DISCOVERABILITY_LENSES)[number]

export interface DiscoverabilityNote {
  lens: DiscoverabilityLens
  /** The finding this was read off. Never free-standing. */
  findingCode: string
  observation: string
  consideration: string
}

// ── Pain interpretations, one per finding ──────────────────────────────────
//
// Keyed by finding code, falling back to category. Written in the register a
// consultant uses with a distributor: concrete, unhurried, no adjectives doing
// work that a noun should do.

interface PainTemplate {
  businessPain: string
  whyItMatters: string
  potentialOpportunity: string
  recommendedDirection: string
}

const BY_CODE: Record<string, PainTemplate> = {
  incomplete_specifications: {
    businessPain:
      'Buyers comparing similar parts may not find the same technical detail on each one, so the comparison has to happen off the site — in a datasheet, or on the phone.',
    whyItMatters:
      'Industrial buyers select on specification. Where a specification is absent, the product is hard to choose with confidence even when it is the right part.',
    potentialOpportunity:
      'Holding specifications as named attributes rather than prose lets the same values drive filtering, comparison and export to a marketplace.',
    recommendedDirection:
      'Agree a specification set per product family, then populate it from the sources that already hold the values.',
  },
  missing_dimensions: {
    businessPain:
      'Dimensions were not consistently available on the inspected product pages, so a buyer checking fit has to look elsewhere.',
    whyItMatters:
      'Fit is often the deciding question, and it is one of the few a buyer cannot resolve by judgement.',
    potentialOpportunity:
      'Recording dimensions as separate named values with their units makes them filterable and reusable across channels.',
    recommendedDirection: 'Capture dimensions as structured attributes with an explicit unit, per product family.',
  },
  missing_weight: {
    businessPain:
      'Weight was not consistently present, which affects both shipping expectations and handling decisions.',
    whyItMatters: 'Weight drives freight cost and handling requirements, so its absence moves a question downstream.',
    potentialOpportunity: 'A populated weight attribute supports shipping calculation and marketplace requirements.',
    recommendedDirection: 'Populate weight with a stated unit as part of the core attribute set.',
  },
  missing_brand: {
    businessPain:
      'Brand was not consistently stated on the inspected product pages, so buyers who search by manufacturer may not find the product.',
    whyItMatters:
      'In distribution, brand is one of the first filters a buyer reaches for. A product without it is effectively outside that path.',
    potentialOpportunity:
      'A consistent brand attribute supports brand-led navigation and makes catalogue coverage visible by supplier.',
    recommendedDirection: 'Normalise brand to a controlled list rather than free text.',
  },
  missing_product_identifier: {
    businessPain:
      'A stable product identifier was not consistently present, which makes the same item harder to reconcile between systems.',
    whyItMatters:
      'Identifiers are how a product stays the same product across a website, an ERP, a marketplace and a customer order.',
    potentialOpportunity:
      'A consistent identifier scheme reduces reconciliation work and is a prerequisite for selling through most marketplaces.',
    recommendedDirection: 'Publish the identifier already held in the source system rather than minting a new one.',
  },
  weak_product_description: {
    businessPain:
      'Descriptions on the inspected pages carried little distinguishing information, so similar products read alike.',
    whyItMatters:
      'A description is where a buyer confirms they have understood the product. Thin text moves that confirmation to a phone call.',
    potentialOpportunity:
      'Descriptions built from the product attributes stay accurate as the data changes and read consistently across the range.',
    recommendedDirection:
      'Generate descriptions from the attribute set, with a human review step, rather than writing each one independently.',
  },
  missing_availability: {
    businessPain:
      'Availability was not consistently shown, so a buyer cannot tell whether an item can be supplied without asking.',
    whyItMatters: 'Availability is often the difference between an order placed now and an enquiry that waits.',
    potentialOpportunity: 'Surfacing the stock position already held in the source system removes that question.',
    recommendedDirection: 'Publish availability from the existing stock record, at whatever granularity is defensible.',
  },
  inconsistent_units: {
    businessPain:
      'Units of measure were written inconsistently across the inspected pages, so values that should compare directly do not.',
    whyItMatters:
      'Two products quoted in different units cannot be filtered or sorted together, and the buyer has to do the conversion.',
    potentialOpportunity:
      'Normalising units to a single convention per attribute makes numeric filtering and comparison possible.',
    recommendedDirection: 'Store the numeric value and its unit separately, and normalise on the way in.',
  },
  no_product_structured_data: {
    businessPain:
      'The inspected product pages did not publish machine-readable product markup, so systems that read the page have to infer its content.',
    whyItMatters:
      'Search engines, AI assistants and marketplace integrations all read structured markup. Without it they interpret the page as prose.',
    potentialOpportunity:
      'Publishing structured product data from the attributes that already exist makes the same content readable by machines.',
    recommendedDirection: 'Emit product structured data generated from the product record, not hand-maintained.',
  },
  incomplete_product_metadata: {
    businessPain:
      'Page-level metadata was incomplete on the inspected pages, which affects how the page is represented when it appears elsewhere.',
    whyItMatters: 'Metadata is what a page looks like before anyone has visited it.',
    potentialOpportunity: 'Metadata derived from the product record stays correct as the catalogue changes.',
    recommendedDirection: 'Generate page metadata from product attributes rather than maintaining it separately.',
  },
  broken_internal_links: {
    businessPain: 'Some internal links on the inspected pages did not resolve, interrupting the path between products.',
    whyItMatters: 'A broken path inside a catalogue ends a buying journey mid-way, and it is invisible until someone hits it.',
    potentialOpportunity: 'Resolving the link structure keeps related products reachable from one another.',
    recommendedDirection: 'Repair the links found here, then check whether the pattern repeats elsewhere.',
  },
  soft_404_pages: {
    businessPain:
      'Some inspected pages returned a success response while showing no usable product content.',
    whyItMatters:
      'A page that reports success but shows nothing is treated as real by systems reading the site, and as broken by the person looking at it.',
    potentialOpportunity: 'Correct status handling keeps the catalogue an accurate picture of what is actually available.',
    recommendedDirection: 'Return an accurate status for pages with no product content.',
  },
  duplicate_pages: {
    businessPain: 'The same product content appeared at more than one address among the inspected pages.',
    whyItMatters:
      'Duplicate addresses split the signals for one product and make it ambiguous which page is the real one.',
    potentialOpportunity: 'A single canonical address per product consolidates that.',
    recommendedDirection: 'Declare one canonical URL per product and point the variants at it.',
  },
  duplicate_categories: {
    businessPain: 'Category pages overlapped among those inspected, so the same products are reachable by several routes.',
    whyItMatters: 'Overlapping categories make the catalogue harder to browse and harder to maintain.',
    potentialOpportunity: 'A single category structure makes navigation predictable and reduces upkeep.',
    recommendedDirection: 'Consolidate the overlapping categories into one hierarchy.',
  },
  no_product_pages_identified: {
    businessPain:
      'No product page could be identified from the markup of the inspected pages, so product data could not be assessed.',
    whyItMatters:
      'Where products are not published as identifiable pages, neither buyers browsing nor systems reading the site can reach them individually.',
    potentialOpportunity:
      'Publishing products as individual pages with structured attributes is the step everything else depends on.',
    recommendedDirection:
      'Confirm whether products are published anywhere on the site, then scope what publishing them would involve.',
  },
}

const BY_CATEGORY: Record<string, PainTemplate> = {
  attributes: {
    businessPain: 'Product attributes were not consistently present on the inspected pages.',
    whyItMatters: 'Attributes are what a buyer filters and compares on; absent ones cannot be used for either.',
    potentialOpportunity: 'A consistent attribute set makes filtering and comparison possible across the range.',
    recommendedDirection: 'Agree the attribute set per product family and populate it from existing sources.',
  },
  specifications: {
    businessPain: 'Technical specifications were not consistently available on the inspected pages.',
    whyItMatters: 'Specification is how an industrial product is selected.',
    potentialOpportunity: 'Structured specifications support comparison and reuse across channels.',
    recommendedDirection: 'Hold specifications as named values rather than prose.',
  },
  descriptions: {
    businessPain: 'Product descriptions carried limited distinguishing information on the inspected pages.',
    whyItMatters: 'Description is where a buyer confirms their understanding of the product.',
    potentialOpportunity: 'Attribute-driven descriptions stay accurate and read consistently.',
    recommendedDirection: 'Build descriptions from the attribute set with a review step.',
  },
  identifiers: {
    businessPain: 'Product identifiers were not consistently published on the inspected pages.',
    whyItMatters: 'Identifiers keep a product the same product across systems and channels.',
    potentialOpportunity: 'A consistent scheme reduces reconciliation and supports marketplace listing.',
    recommendedDirection: 'Publish the identifier already held in the source system.',
  },
  availability: {
    businessPain: 'Availability was not consistently visible on the inspected pages.',
    whyItMatters: 'Availability determines whether a buyer can act now.',
    potentialOpportunity: 'Publishing the existing stock position answers the question in place.',
    recommendedDirection: 'Surface availability from the source system.',
  },
  consistency: {
    businessPain: 'The same kind of value was expressed inconsistently across the inspected pages.',
    whyItMatters: 'Inconsistent values cannot be compared or filtered together.',
    potentialOpportunity: 'Normalising to one convention per attribute makes the data usable.',
    recommendedDirection: 'Normalise on entry and store value and unit separately.',
  },
  structure: {
    businessPain: 'The structure of the inspected pages made product content harder to read reliably.',
    whyItMatters: 'Structure is what lets both people and systems navigate a catalogue.',
    potentialOpportunity: 'A predictable structure supports navigation and machine reading alike.',
    recommendedDirection: 'Agree a consistent page and category structure for product content.',
  },
}

/**
 * Turns one finding into the five-part business reading.
 *
 * The observation is the finding's OWN sample-scoped metric — copied, not
 * rewritten — so the number a customer reads is the number the audit
 * defended. Only the interpretation around it is written here.
 */
export function buildBusinessPain(finding: CatalogFinding): BusinessPain {
  const t = BY_CODE[finding.code] ?? BY_CATEGORY[finding.category] ?? {
    businessPain: `${finding.title} was observed on the inspected pages.`,
    whyItMatters: finding.impact,
    potentialOpportunity: 'Addressing it would make the affected product data usable for filtering and comparison.',
    recommendedDirection: finding.recommendation,
  }

  // Most finding texts already carry their own denominator — "could not be
  // found on 9 of the 12 inspected product pages". Appending the metric to
  // those produced "...on 12 of the 12 inspected product pages. (0 of 12
  // inspected product pages)", which reads as a contradiction because the two
  // numbers count opposite things. So the count is only added where the
  // sentence does not already state one.
  const statesItsOwnCount = /\b\d+\s+of\s+(?:the\s+)?\d+\b/.test(finding.finding)
  const observation = statesItsOwnCount
    ? finding.finding.trim().replace(/\.?$/, '.')
    : `${finding.finding.trim().replace(/\.?$/, '')} (${finding.observedCount} of ${finding.sampleSize} inspected ${finding.sampleUnit}).`

  return {
    findingCode: finding.code,
    observation: assertSupported(`pain.${finding.code}.observation`, observation),
    businessPain: assertSupported(`pain.${finding.code}.businessPain`, t.businessPain),
    whyItMatters: assertSupported(`pain.${finding.code}.whyItMatters`, t.whyItMatters),
    potentialOpportunity: assertSupported(`pain.${finding.code}.potentialOpportunity`, t.potentialOpportunity),
    recommendedDirection: assertSupported(`pain.${finding.code}.recommendedDirection`, t.recommendedDirection),
  }
}

// ── Discoverability: SEO / AEO / GEO ───────────────────────────────────────
//
// The brief permits observations about factors that MAY influence
// discoverability and forbids any claim about actual ranking. So each note
// below is anchored to a finding that was actually recorded, and phrased as a
// consideration rather than a diagnosis. There is no note that exists on its
// own — if the audit did not record the finding, the note does not appear.

const DISCOVERABILITY: Record<string, Array<{ lens: DiscoverabilityLens; consideration: string }>> = {
  no_product_structured_data: [
    {
      lens: 'seo',
      consideration:
        'Search engines read product markup to understand what a page describes. Without it, a product page is interpreted as ordinary text — a potential discoverability consideration, not a measured ranking effect.',
    },
    {
      lens: 'aeo',
      consideration:
        'Assistants answering a product question draw on structured data where it exists. Its absence means any answer has to be inferred from prose.',
    },
    {
      lens: 'geo',
      consideration:
        'Systems that summarise products for a generated answer rely on machine-readable attributes. Unstructured pages give them less to work with.',
    },
  ],
  weak_product_description: [
    {
      lens: 'seo',
      consideration:
        'Where similar products carry similar text, there is little to distinguish the pages from one another. This is a potential discoverability consideration observed on the inspected pages.',
    },
    {
      lens: 'aeo',
      consideration:
        'A question-answering system needs distinguishing detail to match a product to a question. Thin descriptions offer little to match on.',
    },
  ],
  incomplete_specifications: [
    {
      lens: 'aeo',
      consideration:
        'Specification questions are answered from named attributes. Where specifications sit only in prose, they are harder for any system to extract reliably.',
    },
  ],
  incomplete_product_metadata: [
    {
      lens: 'seo',
      consideration:
        'Page metadata determines how a page is represented in a result list. Incomplete metadata was observed on the inspected pages.',
    },
  ],
  duplicate_pages: [
    {
      lens: 'seo',
      consideration:
        'Where one product is reachable at several addresses, it is ambiguous which is the primary page. A canonical declaration resolves that ambiguity.',
    },
  ],
  broken_internal_links: [
    {
      lens: 'seo',
      consideration:
        'Unresolved internal links interrupt the paths through a catalogue that both buyers and crawlers follow.',
    },
  ],
  soft_404_pages: [
    {
      lens: 'seo',
      consideration:
        'Pages returning a success status with no product content are treated as real pages by systems reading the site.',
    },
  ],
}

/** Discoverability notes for the findings this audit actually recorded. */
export function buildDiscoverabilityNotes(findings: CatalogFinding[]): DiscoverabilityNote[] {
  const notes: DiscoverabilityNote[] = []
  for (const f of findings) {
    for (const entry of DISCOVERABILITY[f.code] ?? []) {
      notes.push({
        lens: entry.lens,
        findingCode: f.code,
        observation: `${f.title}: ${f.observedCount} of ${f.sampleSize} inspected ${f.sampleUnit}.`,
        consideration: assertSupported(`discoverability.${f.code}.${entry.lens}`, entry.consideration),
      })
    }
  }
  return notes
}

// ── The case-study layer ───────────────────────────────────────────────────

export interface BusinessValueInput {
  companyName: string
  findings: CatalogFinding[]
  pains: BusinessPain[]
  productPagesInspected: number
  pagesInspected: number
  hasWorkbenchDemo: boolean
}

/**
 * The six-section business reading of the whole audit.
 *
 * Written to be read aloud in a sales conversation. It names the company, uses
 * its actual numbers, and stops at the point where the evidence stops — which
 * is why the financial note exists as a separate, explicit sentence rather
 * than as a hedge buried in a paragraph.
 */
export function buildBusinessValue(input: BusinessValueInput): BusinessValue {
  const { companyName, findings, pains, productPagesInspected, pagesInspected } = input
  const top = pains.slice(0, 3)
  const high = findings.filter((f) => f.priority === 'high')

  const whatWeObserved = findings.length
    ? `We inspected ${pagesInspected} page(s) on the ${companyName} website, ${productPagesInspected} of them product pages, and recorded ${findings.length} product-data finding(s). ${
        high.length ? `${high.length} of them affect fields a buyer needs in order to find and filter a product.` : 'None of them affect the fields a buyer needs in order to find and filter a product.'
      }`
    : `We inspected ${pagesInspected} page(s) on the ${companyName} website, ${productPagesInspected} of them product pages, and recorded no product-data finding against them.`

  const whyThisMatters = top.length
    ? top.map((p) => p.whyItMatters).join(' ')
    : 'Product data on the inspected pages carried the fields a buyer needs. That is the position worth protecting as the catalogue grows.'

  const whereThePainMayAppear = top.length
    ? top.map((p) => p.businessPain).join(' ')
    : 'No pain was evident on the pages inspected.'

  const howAltiusNxtCanHelp = findings.length
    ? 'AltiusNXT works on the product record itself: agreeing the attribute set for each product family, populating it from the sources that already hold the values, and publishing it in a form both buyers and systems can read. The audit points at where to start.'
    : 'AltiusNXT can review a wider sample and confirm whether the position holds across the catalogue.'

  const improvedExperience = input.hasWorkbenchDemo
    ? `A worked example from one of the ${companyName} product pages is available, showing the same product as it appears today alongside the same product with its attributes structured. Every improved value traces back to something already on the page.`
    : findings.length
      ? 'The improved position is a product page where the specifications, identifiers and availability a buyer needs are each present as named values — filterable, comparable, and readable by the systems that list them elsewhere.'
      : 'The current position already carries the fields a buyer needs on the pages inspected.'

  const nextStep =
    'A 15-minute walkthrough covers what was found, what it would take to address, and what a worked example looks like on your own products.'

  const financialNote =
    'Potential opportunity — not quantified in this audit. This review observed product data on a bounded sample of pages. It did not measure sales, traffic or cost, and nothing here should be read as a projection of any of them.'

  return {
    whatWeObserved: assertSupported('value.whatWeObserved', whatWeObserved),
    whyThisMatters: assertSupported('value.whyThisMatters', whyThisMatters),
    whereThePainMayAppear: assertSupported('value.whereThePainMayAppear', whereThePainMayAppear),
    howAltiusNxtCanHelp: assertSupported('value.howAltiusNxtCanHelp', howAltiusNxtCanHelp),
    improvedExperience: assertSupported('value.improvedExperience', improvedExperience),
    nextStep: assertSupported('value.nextStep', nextStep),
    financialNote: assertSupported('value.financialNote', financialNote),
  }
}
